version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/statecrafthq/borg
    steps:
      - checkout
      - run: go get gopkg.in/kyokomi/emoji.v1
      - run: go get github.com/urfave/cli
      - run: go get github.com/twpayne/go-geom
      - run: go get github.com/buger/jsonparser
      - run: go get gopkg.in/cheggaaa/pb.v1
      - run: go get github.com/cheggaaa/pb
      - run: go build
      - store_artifacts:
          path: /go/src/github.com/statecrafthq/borg/borg