version: 2
jobs:
  build:
    machine: true
    working_directory: /dist
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker build -t statecraft/borg:v${CIRCLE_BUILD_NUM} ./dist/.
      - run: docker push statecraft/borg:v${CIRCLE_BUILD_NUM}